version: '2'
template:
  name: "Multiple Deployment Options"
  description: "Deploy a Fibonacci microservice to different compute options to compare them."
  required:
    - build
    - repo
    - deploy

toolchain:
  name: 'multiple-deployment-options-{{timestamp}}'

services:
  repo:
    service_id: githubpublic
    parameters:
      repo_name: 'multiple-deployment-options'
      repo_url: 'https://github.com/IBM-Bluemix/multiple-deployment-options'
      type: fork
      has_issues: false
  build:
    service_id: pipeline
    parameters:
      services:
        - repo
      name: '{{services.repo.parameters.repo_name}}'
      ui-pipeline: true
      configuration:
        content:
          $text: pipeline.yml
        env:
          REPO: repo
          CF_APP_NAME: '{{form.pipeline.parameters.deploy-app-name}}'
          SPACE_NAME: '{{form.pipeline.parameters.deploy-space}}'
          ORG_NAME: '{{form.pipeline.parameters.deploy-organization}}'
          REGION_ID: '{{form.pipeline.parameters.deploy-region}}'
          BLUEMIX_API_KEY: '{{form.pipeline.parameters.deploy-bluemix-api-key}}'
          CLUSTER_NAME: '{{form.pipeline.parameters.deploy-cluster-name}}'
          IMAGE_NAME: '{{form.pipeline.parameters.deploy-image-name}}'
          CONTAINER_ORG_NAME: '{{form.pipeline.parameters.container-organization}}'
          CONTAINER_REGION_ID: '{{form.pipeline.parameters.container-region}}'
          CONTAINER_SPACE_NAME: '{{form.pipeline.parameters.container-space}}'
        execute: true

form:
  pipeline:
    parameters:
      deploy-app-name: 'fibonacci-service'
      deploy-bluemix-api-key: ''
      deploy-cluster-name: ''
      deploy-image-name: 'registry.ng.bluemix.net/<namespace>/fibonacci:latest'
    schema:
      $ref: deploy.json
