version: '2'
template:
  name: "Multiple Deployment Options"
  description: "Deploy a Fibonacci microservice to different compute options to compare them."
  required:
    - build
    - repo
    - deploy

toolchain:
  name: 'multiple-deployment-options-{{timestamp}}'

services:
  repo:
    service_id: githubpublic
    parameters:
      repo_name: 'multiple-deployment-options'
      repo_url: 'https://github.com/IBM-Cloud/multiple-deployment-options'
      type: fork
      has_issues: false
      enable_traceability: false
  build:
    service_id: pipeline
    parameters:
      services:
        - repo
      name: '{{services.repo.parameters.repo_name}} ({{form.pipeline.parameters.branch-name}})'
      ui-pipeline: true
      configuration:
        content:
          $text: pipeline.yml
        env:
          GIT_REPO: repo
          GIT_BRANCH: '{{form.pipeline.parameters.branch-name}}'
          API_KEY: '{{form.pipeline.parameters.api-key}}'
          REGION_ID: '{{form.pipeline.parameters.target-region}}'

          CF_APP_NAME: 'fibonacci-service'
          SPACE_NAME: '{{form.pipeline.parameters.target-space}}'
          ORG_NAME: '{{form.pipeline.parameters.target-organization}}'

          CLUSTER_REGION: '{{form.pipeline.parameters.target-cluster-region}}'
          CLUSTER_NAME: '{{form.pipeline.parameters.target-cluster-name}}'
          REGISTRY_REGION_ID: '{{form.pipeline.parameters.registry-region}}'
          REGISTRY_NAMESPACE: '{{form.pipeline.parameters.registry-namespace}}'
          IMAGE_NAME: '{{form.pipeline.parameters.image-name}}'
          RESOURCE_GROUP: '{{form.pipeline.parameters.target-resource-group}}'
        execute: false

form:
  pipeline:
    parameters:
      image-name: 'fibonacci'
      branch-name: 'master'
    schema:
      $ref: deploy.json
